### ISSUE TITLE
Add monthly reports

### ISSUE THREAD

**Issue by shawnbuckles** [distantnative/retour-for-kirby#103]
Adding monthly click reports will allow the plugin to be used as an affiliate link monitoring tool.

**Comment by distantnative** [comment]
Maybe I don't understand correctly what you mean, but the stats are already available in year, month, week and day view.

**Comment by shawnbuckles** [comment]
Yes, the visual stats are. 
I mean a way to show the monthly hits, per link, per month, as stats instead of a graph.
In other words, a way to filter the lower section (table with redirects and hits).

**Comment by distantnative** [comment]
Ah, got you know. That should be not too complicated. Guess the most difficult one would be the UI. Would they be react to the existing filter buttons?

**Comment by shawnbuckles** [comment]
I guess that would work, simply type in the date range or month and hit enter?

**Comment by distantnative** [comment]
No, typing in is horrible because you have to handle all input validation etc. I meant the existing links to switch between year, month etc. and arrows to move backwards, forwards.

**Comment by distantnative** [comment]
The next release will include a custom date interval picker and the table data will respond to this date interval as well. Preview:

<img width="1207" alt="Screen Shot 2019-12-01 at 14 56 48" src="https://user-images.githubusercontent.com/3788865/69915036-e4fad280-144a-11ea-9ae3-41cda4806f17.png">

I think, this will solve your requests very nicely. ✅
