### ISSUE TITLE
Grouping redirects

### ISSUE THREAD

**Issue by shawnbuckles** [distantnative/retour-for-kirby#104]
Add a way to group or categorize redirects for better organization.

**Comment by distantnative** [comment]
Could you provide some use cases?

**Comment by shawnbuckles** [comment]
Yes, for example, group affiliate links you want to monitor.

**Comment by distantnative** [comment]
To be honest I am not seeing myself to implement this feature anytime soon. It just introduces a lot of complexity in terms of UI handling and data storage that I'm not fond of tackling at this point in time. Just want to be transparent about it.

**Comment by distantnative** [comment]
I will close this for now
