### ISSUE TITLE
TypeError: document.querySelector(...) is null

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#105]
Using Retour with the latest Kirby `develop` branch throws `TypeError: document.querySelector(...) is null` on save. This relates to the following code:

```js
document.querySelector("svg defs").innerHTML+="\n<symbol id=\"icon-retour\" viewBox=\"0 0 16 16\">\n  <use xlink:href=\"#icon-undo\" transform=\"translate(7.5,7.5) rotate(170) translate(-7.5,-7.5)\"></use>\n</symbol>\n";
```

My guess is, this has to do with change in the core to support icon plugins?

**Comment by distantnative** [comment]
Tha could be. I have to check it later.

**Comment by distantnative** [comment]
Got fixed in the core. Will still leave it open until I switched to new custom icon plugin method.
