### ISSUE TITLE
Error: The JSON response from the API could not be parsed. Please check your API connection.

### ISSUE THREAD

**Issue by afbora** [distantnative/retour-for-kirby#106]
When i set user language as `Turkish`, console output in plugin page:

> app.js:formatted:14718 Error: The JSON response from the API could not be parsed. Please check your API connection.  at app.js:formatted:14441

> app.js:formatted:14441 Uncaught (in promise) Error: The JSON response from the API could not be parsed. Please check your API connection. at app.js:formatted:14441

app.js:formatted:14718 

```
Xm.config.onError = function(t) {
    y.debug && window.console.error(t),
    403 !== t.code || "Unauthenticated" !== t.message && "access.panel" !== t.key || Km.dispatch("user/logout", !0) // 14718.line
}
```

app.js:formatted:14441

```
try {
    return JSON.parse(t)
} catch (e) {
    throw new Error("The JSON response from the API could not be parsed. Please check your API connection.") // 14441.line
}
```

Kirby 3.2.5 Stable

**Comment by distantnative** [comment]
@afbora 
Would it be able that you check what the response actually includes if not JSON (I assume a more specific PHP error). Thanks.

**Comment by afbora** [comment]
As time passed, I forgot which project I get this error and now I can't reproduce it 😅 
When I see the error again, I will share more detailed information.
Thank you @distantnative
