### ISSUE TITLE
Add option to disable logs

### ISSUE THREAD

**Issue by fabianmichael** [distantnative/retour-for-kirby#109]
Scenario: I would like to use your plugin for a client, who has a dev, a staging- and a live server and we are 2 developers in total, who work constantly on the project. As a binary blob, such as an SQLite database is always problematic for syncing data between also instances of a website, it would be very handy having an option to turn off the feature complety.

For now, I just decided to add the logs folder to `.gitignore` and hide all logging-related features in the panel using a custom CSS file. However, it would feel way more elegant to have an option for really disabling the feature.

**Comment by distantnative** [comment]
Makes total sense to make that optional!

**Comment by distantnative** [comment]
Looks so naked 😱

<img width="1233" alt="Screen Shot 2019-10-18 at 20 17 36" src="https://user-images.githubusercontent.com/3788865/67118055-69b7c700-f1e4-11e9-9c5a-ff9a84048ce2.png">

**Comment by fabianmichael** [comment]
@distantnative Let’s call it minimalistic, that sounds less harsh! 😂

**Comment by distantnative** [comment]
✅ could you try out the `develop` branch and see if it works for you?

**Comment by fabianmichael** [comment]
@distantnative Thanks for you (lightning-fast) help! I just downloaded it and gave it a quick try. Seems to work fine for my simple test case. No logs where creaated and the redirects worked fine.

I just wondered, why retour does not use namespaced options, like other plugins?
![Bildschirmfoto 2019-10-21 um 14 54 14](https://user-images.githubusercontent.com/395617/67206882-c7315b00-f412-11e9-80f2-1a4266ea3514.png)

**Comment by distantnative** [comment]
I was thinking that the option keys get suuuuper long. And thought `retour` might be prefix enough. But maybe you are right and I should jump back in line and prefix them with `distantnative`?

**Comment by fabianmichael** [comment]
@distantnative I know, it doesn’t look nice, but it has several advantages: First of all, you’ll never pollute Kirby’s option namespace. But probably the most important thing, that I learned from writing a rather extensive plugin: You can define all options and default values within `Kirby::plugin()`. When accessing an option several times, you don’t have to specify the fallback value every time (which is especially handy for more complex option values, such as strings or arrays). Having all available options in one place also gives you a better overview of the available ones.

Only bad thing for retour is, that this would be a breaking change, though.

**Comment by distantnative** [comment]
> Only bad thing for retour is, that this would be a breaking change, though.

Not quite true. I had the namespace in 2.0 and only removed it for 2.1, but if I'll include it again it will be just like in 2.0

**Comment by fabianmichael** [comment]
I would recommend to include it again, so the plugin options will just work like in the majority of plugins (despite it’s not looking very nice). That might be less confusing to most users.

**Comment by distantnative** [comment]
> When accessing an option several times, you don’t have to specify the fallback value every time

I have troubles getting that going. I always get `null` when calling `option()` without a fallback.

**Comment by distantnative** [comment]
Ah, I think I found my mistake

**Comment by distantnative** [comment]
Would be happy if you could test it again.

**Comment by fabianmichael** [comment]
@distantnative I will do that, as soon as Kirby 3.3.0 RC1 is released, as I cannot upgrade my project before without too many issues.

**Comment by distantnative** [comment]
@fabianmichael luckily, I think the RC will be out today :)
