### ISSUE TITLE
Add user-defined paths to ignore

### ISSUE THREAD

**Issue by jschopplich** [distantnative/retour-for-kirby#116]
Several websites utilizing Retour (which is one of the most useful Kirby plugins — thanks for that!) log a lot of requests from bots which I'd like to ignore all along. For example:

- `.env`
- `wp`
- `wp-login.php`
- `.git/index`
- etc.

I'd appreciate an option where I can define paths, which will not be logged at all. As a result, the overview of failures would be a bit more unpolluted.

What do you think?

**Comment by distantnative** [comment]
Basically an option saying "I want these to keep failing, but please don't log them"?
Would you say a config option is sufficient without additional UI in the Panel?

**Comment by jschopplich** [comment]
Exactly. 😄👍 

I guess an UI element would overload. A config option sounds beautiful.

**Comment by distantnative** [comment]
✅
