### ISSUE TITLE
"Select" button gives "t.models is undefined"

### ISSUE THREAD

**Issue by Pandorrrrrra** [distantnative/retour-for-kirby#117]
Testing your great plugin, I came across this error "t.models is undefined" if I click the button "Select" next to the "Redirect to" field.

Tested with:
Kirby 3.3.0
Firefox 70.0.1
mac OS Sierra 10.12.6

![Bildschirmfoto 2019-11-06 um 22 37 56](https://user-images.githubusercontent.com/50926857/68340476-cffa8000-00e6-11ea-91cc-828db1d03208.png)

![Bildschirmfoto 2019-11-06 um 22 37 24](https://user-images.githubusercontent.com/50926857/68340488-d4bf3400-00e6-11ea-98b6-2bc93c9ccedd.png)

**Comment by distantnative** [comment]
Does the issue remain if you use the just released 2.1 version?

**Comment by Pandorrrrrra** [comment]
Yes somehow I still get the same error with 2.1 version.

**Comment by medienbaecker** [comment]
I get a similar error clicking the Select button:

![image](https://user-images.githubusercontent.com/7975568/68493107-1d443200-024c-11ea-9d8a-c94f0f67150a.png)

(Version 2.1.0 with Kirby 3.3.0)

**Comment by distantnative** [comment]
Urgh, sorry guys. I’ll try to get to this ASAP, but it’s a bit tricky being on the road

**Comment by distantnative** [comment]
✅
