### ISSUE TITLE
Don't Write to the site/ Folder

### ISSUE THREAD

**Issue by Jayshua** [distantnative/retour-for-kirby#123]
For security reasons the user that my webserver runs under is only allowed to write to the `content` and `media` folders. Specifically it doesn't have permissions to write to the `site` directory. I have a separate directory outside of the web root (and therefore not accessible over the internet) where I've configured retour to put its database and redirects.yml file.

This works, but retour wants to write a .updated file to its plugin folder. I've worked around this for now by giving the webserver permission to write that specific file. Was thinking it would be better to make this path configurable as well though. Maybe replace the `distantnative.retour.config` and `distantnative.retour.database` options with a `distantnative.retour.directory` option where it can write whatever it likes? Or just another option for the .updated file.

**Comment by distantnative** [comment]
Understood. I don't think I will replace the existing options - I don't want to creat another breaking change.

But I will look into adding another option or just reuse `distantnative.retour.config` .

And I will look into maybe having the directory option as fallback if no individual option is set.

**Comment by distantnative** [comment]
Actually ended up just adding a `distantnative.retour.updated` option.
