### ISSUE TITLE
Upgrade from 2.0.3 to 2.1.1 failed 

### ISSUE THREAD

**Issue by macx** [distantnative/retour-for-kirby#125]
After upgrading I get this error in the front-end and the panel:

```
Warning: file_put_contents([...]/src/plugins/retour-for-kirby): failed to open stream: Is a directory in [...]/dist/kirby/src/Toolkit/F.php on line 792
```

Notice: The plugin directory is not located in the default folder, but this doesn't seem to be a problem with retour in the 2.0.3 version.

```php
$kirby = new Kirby([
  'roots' => [
    'index'    => __DIR__,
    'base'     => $base,
    'content'  => $base . '/dist/content',
    'site'     => $src = $base . '/src',
    'storage'  => $storage = $src . '/storage',
    'accounts' => $storage . '/accounts',
    'cache'    => $storage . '/cache',
    'sessions' => $storage . '/sessions'
  ]
]);
```

**Comment by distantnative** [comment]
Maybe it is realted to this:
https://github.com/distantnative/retour-for-kirby/issues/124

WOuld be interesting to know if it works with the soon-to-be released 2.2.0 - release candidate for testing: https://github.com/distantnative/retour-for-kirby/releases/tag/2.2.0-rc.1

**Comment by distantnative** [comment]
Please try it with 2.2.0 - and reopen if it still does not work. Thanks :)

**Comment by macx** [comment]
@distantnative It's working with 2.2.0. Thanks!
