### ISSUE TITLE
Options / config ignored if using array notation

### ISSUE THREAD

**Issue by adamkiss** [distantnative/retour-for-kirby#126]
Using latest 2.2.0-rc1 and Kirby 3.3.1, if I use the array notation for config, it gets ignored:

```
'distantnative' => [
    'retour' => [
        'option' => 'value'
    ]
]
```

![CleanShot 2019-12-04 at 16 29 20](https://user-images.githubusercontent.com/481362/70155817-3f966780-16b3-11ea-985b-de571f6ef4f4.png)
![CleanShot 2019-12-04 at 16 29 45](https://user-images.githubusercontent.com/481362/70155862-4e7d1a00-16b3-11ea-8855-528f0f66200e.png)

if I use the dot notation in flat array, it works:

```
'distantnative.retour.option' => 'value'
```

![CleanShot 2019-12-04 at 16 27 16](https://user-images.githubusercontent.com/481362/70155694-0827bb00-16b3-11ea-85b3-189554f3a319.png)

**Comment by distantnative** [comment]
Closing it here because it seems to be a general Kirby issue:
https://github.com/getkirby/kirby/issues/2343
