### ISSUE TITLE
Upgraded - no redirects list.

### ISSUE THREAD

**Issue by simoncox** [distantnative/retour-for-kirby#127]
Just upgraded to 2.20 (7th Dec) and when installed I had no redirects in the list (was 120). Had a list of failures but no redirects. The redirects.yml file still exists in site/config and it the original one.

**Comment by distantnative** [comment]
Hi @simoncox - that doesn’t sound ideal 😞
Do you have any options set for retour? Or running with the defaults?

**Comment by simoncox** [comment]
Defaults only - not clever enough to do options. :)

**Comment by distantnative** [comment]
@simoncox And there are no console errors?

Otherwise can you add the following to the `system.loadPlugins:after` cool in `site/plugins/retour/src/config/hooks.php`?

```php
    'system.loadPlugins:after' => function () {
        Update::check();

        // add this:
        dump(Retour::root('redirects'));
        die();
    }
```

And what is the output when you try to access your site then?

**Comment by distantnative** [comment]
I will close this for now. Let me know if you still encounter the problems.
