### ISSUE TITLE
Invalid form submission result in corrupted redirects.yml

### ISSUE THREAD

**Issue by LeBenLeBen** [distantnative/retour-for-kirby#137]
Start with a bunch of redirections in your `redirects.yml`.

1. Toggle the form to add a new redirection
2. Submit the form *empty* with enter or by clicking "create"
3. No errors are displayed for the client but in the network panel of the browser console, you can see requests that failed with a 500 error code
4. Refresh the page -> redirections list is empty

Adding a redirection with an empty form seems to add the following to the `redirects.yml`:

```yaml
-
  status: disabled
```

This line prevents redirections list from being loaded.

Browser: Firefox
Kirby: 3.3.2
Retour: 2.2.0

**Comment by distantnative** [comment]
Urgs... the form shouldn't allow submission in that case

**Comment by distantnative** [comment]
✅
