### ISSUE TITLE
Hits are counted twice

### ISSUE THREAD

**Issue by LeBenLeBen** [distantnative/retour-for-kirby#138]
On the retour dashboard, I click on the link icon on the left of a redirection to open it. It gets open in a new tab. I close this tab and refresh the retour dashboard. The "hits" value for the link I just clicked was bumped from `0` to `2`. It should be `1`.

Multilingual website: yes
Browser: Firefox
Kirby: 3.3.2
Retour: 2.2.0

**Comment by distantnative** [comment]
Hmm I cannot reproduce the problem during my first tests. I get from `0` to `1`.
Could you share more information about the redirects (e.g. the config file)?

Do you have any custom routes set up?

**Comment by LeBenLeBen** [comment]
I have a special setup where a `public` directory is used as root by the webserver:

```php
include '../vendor/autoload.php';

$kirby = new Kirby([
  'roots' => [
    'index'    => __DIR__,
    'base'     => $base = dirname(__DIR__),
    'content'  => $base . '/content',
    'site'     => $base . '/site',
    'storage'  => $storage = $base . '/storage',
    'accounts' => $storage . '/accounts',
    'cache'    => $storage . '/cache',
    'sessions' => $storage . '/sessions',
  ]
]);

echo $kirby->render();
```

Hence a custom Retour config to have the files at the right place:

```php
return [
  'distantnative.retour.deleteAfter' => 6,
  'distantnative.retour.config' => '../storage/retour/redirects.yml',
  'distantnative.retour.database' => '../storage/retour/retour.sqlite',
  'distantnative.retour.updated' => '../storage/retour/.updated'
];
```

I have indeed a couple of custom routes:

```
'([a-z]{2})/team/(:any)',
'team/(:any)',
'csrf-token',
'contact-form',
'([a-z]{2})/blog/tags/(:all)',
'blog/tags/(:all)',
'([a-z]{2})/jobs/(:all)',
'jobs/(:all)',
'weather'
```

All entries seems to trigger the double hits, here are a couple for example:

```
-
  from: en/blog/functional-programing-in-php
  to: en/blog/functional-programming-in-php
  status: "301"
  hits: "2"
  last: 2019/12/20 15:03:48
-
  from: (:alpha)/blog/tags/open-data
  to: $1/blog/tags/open+data
  status: "301"
  hits: "2"
  last: 2019/12/20 15:09:24
-
  from: awards
  to: /
  status: "301"
  hits: "1"
  last: 2019/12/20 15:04:22
```

I think there's indeed a conflict with custom routes, sometimes they take over and Retour can't catch then to redirect properly and some other time the hits is recorded twice. I'll check my routes to be sure they are properly done for Kirby 3 as they are quite old now and maybe not 100% correctly defined.

**Comment by distantnative** [comment]
Thanks for the detailed answer. That’ll help trying to reproduce the bug. I can’t promise though yet when I’ll get to it as the next days are quite busy.

**Comment by LeBenLeBen** [comment]
I commented out all my custom routes and I still have some hits counted twice. Also some others aren't counted at all. Any idea where to look next?

**Comment by distantnative** [comment]
Just to be sure, you are on Retour 2.3.1?

My current guess would be that the origin is somewhere related to multilanguage, but I couldn't find any real clue yet unfortunately.

**Comment by LeBenLeBen** [comment]
Yes I upgraded to 2.3.1 before testing again.

**Comment by distantnative** [comment]
@LeBenLeBen Would it be possible to share the whole setup (nico@getkirby.com)?

**Comment by bvdputte** [comment]
FWIW; I am testdriving retour in one of my installs, and failures are counted twice, whilst redirects seem to be counted correct...

**Comment by bvdputte** [comment]
Hmm, I can replicate the "double hits" on redirects now too.

In my tests, these occur **when I redirect from localized paths**:
- `de/test`-> `de`: double hit 👎 (_de = home page in german (non-default language)_)
- `en/test` -> `products`: double hit 👎 (_products = product page in English (default language)_)
- `xxx`-> `home`: single hit 👍 (_picked the home page from the "pages-select"_)

Maybe this can point you in the right direction?

**Comment by bvdputte** [comment]
I have no insights in the kirby bootstrap process internally, but I did find a `kirby\src\Cms\LanguageRouter`-class. Maybe, in case of multilingual websites, there's an internal overload from the router to the languagerouter that registers double "hits"?

**Comment by distantnative** [comment]
Thanks you two already for so much context, trying to dig in right now.

**Comment by bvdputte** [comment]
@distantnative, I don't know if it's something, but Bastian once had created flowcharts with some kind of visual tool of the bootstrap process. I think they got posted to slack, or even to K-next notion... Maybe he still has them around somewhere?

**Comment by distantnative** [comment]
Ok, I think I tracked down the issue:

The core changed significantly how it handles multilang routes. The new implementation makes use of `$route→next()` if no specific version for this language can be found:
https://github.com/getkirby/kirby/blob/master/src/Cms/LanguageRoutes.php#L43

However, my tracking relies on the `route:after` hook, looking at whether the result is empty after the route. Nevertheless, this hook gets actually called after every route until a result has been found:
https://github.com/getkirby/kirby/blob/master/src/Http/Router.php#L115-L117

So my implementation is counting multiple hits each time multiple routes are called before a result gets returned - and that happens a lot of times in multilang setups.

I don't really know a solution yet. There aren't really other hooks to use around. This would likely require changes in Kirby's core.

**Comment by distantnative** [comment]
I think I just found a solution ✅

**Comment by LeBenLeBen** [comment]
Thanks for looking into this! Do you think you'll be able to release a new version sometime soon so I can try it?

**Comment by distantnative** [comment]
@LeBenLeBen I thought I would release it very soon. Then stuff in 3.4 came up that I would like to incorporate... have to decide what to do with that
