### ISSUE TITLE
Fail silently when web server user can't write in redirects.yml

### ISSUE THREAD

**Issue by LeBenLeBen** [distantnative/retour-for-kirby#145]
Let's say your webserver user (`www-data` for example) have the rights to read but not write the `redirects.yml`; if you try to delete an entry in the list of redirections, it fails silently without doing anything.

It would be great if a message could be displayed guiding the user to the file permissions required.

**Comment by distantnative** [comment]
How could they create redirects then in the first place if there are no write permissions?

**Comment by LeBenLeBen** [comment]
I personnaly copied the file I had in dev to the remote server. But I get your point. Does an error is triggered when you want to create an entry and it can't be written? Didn't try that.

I agree it's an edge case and won't be mad if you think it's not worth fixing ;-)

**Comment by distantnative** [comment]
✅ Will be fixed in upcoming version 2.32.
