### ISSUE TITLE
"could not load driver"

### ISSUE THREAD

**Issue by mxdvl** [distantnative/retour-for-kirby#146]
Do you have any idea what could be causing this `could not load driver` error?

`$this->connection = new PDO($this->dsn, $options['user'], $options['password']);`

You can see the full whoops on my website here: <https://www.mxdvl.com/404>

**Comment by distantnative** [comment]
Sounds like your server setup is missing sql/sqlite support.

**Comment by mxdvl** [comment]
Indeed, running `sudo apt-get install sqlite php-sqlite3` fixed it!

**Comment by distantnative** [comment]
Great! :)
