### ISSUE TITLE
Version 3.1 not working?

### ISSUE THREAD

**Issue by iv-agatha** [distantnative/retour-for-kirby#148]
I have **Kirby 3.3.3** and the plugin installed via composer but the redirect functionality doesn't seem to be working. Is there an additional configuration needed? Should it be renamed from `retour-for-kirby` to just `retour`? I tried doing that but got an error: `Fatal error: Uncaught Error: Class 'distantnative\Retour\Version' not found in /.../site/plugins/retour/src/config/hooks.php on line 29`

**Comment by distantnative** [comment]
I'm working on a version 3.0.0 of Retour which will solve this.
