### ISSUE TITLE
allow callbacks for config and database folder

### ISSUE THREAD

**Issue by bnomei** [distantnative/retour-for-kirby#149]
using retour on kirby installations with a custom folder setup is a bit complicated right now. for example with my deploy chain i have only one persistent folder "storage" and that is a symlink.

the following works but that is still a hardcoded root.
```php
'distantnative.retour.config' => realpath(__DIR__ . '/../../storage') . '/retour.yml',
'distantnative.retour.database' => realpath(__DIR__ . '/../../storage') . '/retour.sqlite',
```

what i would love to have is the option allowing for a callback as well. like this...
```php
'distantnative.retour.config' => function () {
    return realpath(kirby()->roots()->storage()) . '/retour.yml';
},
'distantnative.retour.database' => function () {
    return realpath(kirby()->roots()->storage()) . '/retour.sqlite';
},
```

> I need `realpath` for my symlinked storage folder.

all you need to do is add these lines here:
https://github.com/distantnative/retour-for-kirby/blob/master/src/models/Retour.php#L46

```php
$roots['redirects'] = is_callable($roots['redirects']) ? $roots['redirects']() : $roots['redirects'];
$roots['logs'] = is_callable($roots['logs']) ? $roots['logs']() : $roots['logs'];
```

**Comment by distantnative** [comment]
✅
