### ISSUE TITLE
provide actual example how to use config value

### ISSUE THREAD

**Issue by bnomei** [distantnative/retour-for-kirby#150]
the config array show in https://distantnative.com/retour/docs
is kind of confusing since one does not use them as a one array but as independent options.

```php
'distantnative.retour.logs' => false,
``` 

but following might seem possible for kirby beginners or less experienced php devs. but it is invalid.

```php
'distantnative.retour' => [
    'logs' => false,
    'deleteAfter' => 3,
],
```

**Comment by distantnative** [comment]
That is a bug in Kirby itself: https://github.com/getkirby/kirby/issues/2343

**Comment by bnomei** [comment]
understood but... so you are setting an example that will cause a bug? ;-)

**Comment by distantnative** [comment]
Let's see if the bug will fixed first or my docs updated
