### ISSUE TITLE
question about matching of url

### ISSUE THREAD

**Issue by bnomei** [distantnative/retour-for-kirby#153]
if i enter the path `arbeiten/alle-arbeiten` will retour also match a `https://example.com/arbeiten/alle-arbeiten/` with a trailing slash? 

what about the other way around?
`arbeiten/alle-arbeiten/` matches `https://example.com/arbeiten/alle-arbeiten` ?

**Comment by distantnative** [comment]
Have you tried it? 😆

**Comment by bnomei** [comment]
i did and ran into an issue but seems to be gone now. will see if this pops up again. 🤷‍♂
