### ISSUE TITLE
The (:any) placeholder only matches sub-paths containing slashes?

### ISSUE THREAD

**Issue by fvsch** [distantnative/retour-for-kirby#155]
My `site/config/redirects.yml` contains:

```
- { status: 301, from: articles/(:all), to: 'a-cool-test' }
```

I'm loading a page at the URL `/articles/some-article`, which itself references files with URLs like:
- `/articles/some-article/my-image.png`
- `/articles/some-article/other-image.svg`

The image requests get redirected, but the request for `/articles/some-article` doesn't.

I expected the `(:all)` placeholder to also match `some-article`.

**Comment by distantnative** [comment]
Hmmm it should 
https://github.com/getkirby/kirby/blob/0330c0ae4214cde349710b099a770fffd0971b4e/src/Http/Route.php#L64

**Comment by fvsch** [comment]
My mistake, I skipped this part of the docs:

> Only paths without existing pages or custom routes can be redirected.

The page I was testing did exist at `content/articles/some-article`, so that got served by Kirby and Retour didn't have a chance to catch the request. Good way to learn that it runs last. :)

For anyone who's trying to use Retour to "hide" a content subfolder, you can do that with a couple routes in your config:

```php
return [
  'routes' => [
    // Redirect requests for 'articles/*'
    [
      'pattern' => 'articles/(:all)',
      'action' => function($path) {
        return Header::redirect('/' . $path, 301);
      }
    ],
    // Serve from `content/articles` articles without the 'articles' folder in the URL.
    // Warning: `content/articles/some-article` will be used over `content/some-article`.
    [
      'pattern' => '(:any)',
      'action' => function($slug) {
        if ($article = page('articles/' . $slug)) {
          return $article;
        }
        return $this->next();
      }
    ]
  ]
];
```
