### ISSUE TITLE
PDOException: could not find driver

### ISSUE THREAD

**Issue by hdodov** [distantnative/retour-for-kirby#160]
![image](https://user-images.githubusercontent.com/5570098/78258310-b6c5f600-7503-11ea-956d-d3d4e059f985.png)

**Comment by hdodov** [comment]
This happens when the SQLite Apache module is not enabled. To fix this:

1. Install the module:

```
sudo apt-get install php7.3-sqlite3
```

2. Restart Apache:

```
sudo systemctl reload apache2.service 
```

@distantnative you could put this in the README.

**Comment by distantnative** [comment]
Reopened so I don't forget to add it to the docs

**Comment by distantnative** [comment]
✅ Added locally, will be published with Retour 3 release.

**Comment by lukehatfield** [comment]
@hdodov solution worked for me, but I had to run this instead for step 2 as I'm running php 7.4...

`sudo apt-get install php7.4-sqlite3`
