### ISSUE TITLE
Hi have such trouble.

### ISSUE THREAD

**Issue by alkachur** [distantnative/retour-for-kirby#162]
WebSocket connection to 'wss://site.com:54624/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Mixed Content: The page at 'https://.../plugins/retour' was loaded over HTTPS, but requested an insecure resource 'http://.../api/retour/stats?view=month&from=2020-05-01&to=2020-05-31'. This request has been blocked; the content must be served over HTTPS.

**Comment by distantnative** [comment]
That is very weird, as the plugin doesn’t define with which protocol (http vs. https) is loaded. What other plugins are you using? What server is this running on?

**Comment by alkachur** [comment]
Yes, you was right this port is closed by hosting provider, so this is a security problem, not a plugin.
