### ISSUE TITLE
Request for /api/retour/stats/ (with trailing slash) can be redirected on specific setups

### ISSUE THREAD

**Issue by fvsch** [distantnative/retour-for-kirby#163]
This is kind of an edge case. I have a `.htaccess` redirect that redirects all non-folder requests ending in `/` to the non-slash equivalent.

The redirect seems to make the request for `/api/retour/stats/` fail (I think the redirection might be loosing the session cookie in my case, but maybe it's only because the redirection is badly set up and redirects to HTTP then back to HTTPS -> the origin change probably looses any cookie).

It looks like Retour doesn't use trailing slashes for requests to other resources, including `/api/retour/redirects` and `/api/retour/fails`.

Not sure if the extra slash in `/api/retour/stats/?…` is worth investigating on your side.
Feel free to close this bug if not. :)

**Comment by distantnative** [comment]
You are actually right, `stats` is the only one I am calling with a trailing slash: https://github.com/distantnative/retour-for-kirby/blob/master/src/store.js#L137

I can certainly change that - I don't think it will have any issues for everyone else if I change it.

On the other hand, I would argue that your `.htaccess` should be setup in a way maybe not to mess with API calls ;)

**Comment by fvsch** [comment]
Oh, definitely :D

**Comment by fvsch** [comment]
For any passerby interested in the Apache rewrite rules, they look like:

```
# Redirect URLs with trailing slashes to no-slash
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !api
RewriteRule ^(.*)/$ https://domain.tld/$1 [L,R=301]
```

**Comment by distantnative** [comment]
✅ will be fixed in Retour 3
