### ISSUE TITLE
Remember pagination choice

### ISSUE THREAD

**Issue by fvsch** [distantnative/retour-for-kirby#164]
By default the Retour UI shows 10 requests/fails at a time.
I tend to bump it to "50" or "all", but on every page refresh it's back at 10.

It would be great if Retour could remember my preference, maybe in localStorage?
Another option would be to add an option like `'distantnative.retour.itemsPerPage'`.

**Comment by distantnative** [comment]
I will have a look at this when rewriting Retour for Kirby 3.4 (which I am currently waiting for).
3.4 will introduce a lot of new UI components, including a table - and I will throw out all my old custom cruft in favor of the native components.

**Comment by distantnative** [comment]
✅ will be in Retour 3

Storing the perPage option in localStorage
