### ISSUE TITLE
Access to content representations get logged as failures?

### ISSUE THREAD

**Issue by fvsch** [distantnative/retour-for-kirby#165]
Hi Nico and thanks for a great plugin! The "Failures" log in particular is super helpful to catch issues such as dead links (internal and incoming).

My logs seem dominated by accesses to:

- `/feed.xml`
- `/feed.json`

Both are [content representations](https://getkirby.com/docs/guide/templates/content-representations) of a single page (`/feed`), and seem to work fine in my tests when accessed directly or through several feed readers.

![Screenshot](https://user-images.githubusercontent.com/243601/83514072-36a41880-a4d3-11ea-9897-642c1dee5703.png)

I haven't seen this issue reported before in this repo, but I guess it could be an upstream bug you already reported.

**Comment by distantnative** [comment]
Oh this is definitely something to look into.
Will put it in the list for the next big release (to be released after Kirby 3.4 is out)

**Comment by distantnative** [comment]
@fvsch I doesn't create failures in my test for Retour 3. Now it could be that this has been fixed by changes to how I resolve routes. But it could also mean I am not testing it right.

Are you saying that the hit counter also increases when you yourself access those and get a valid response (e.g. the JSON)?

**Comment by fvsch** [comment]
I'm getting failure hits when accessing those routes myself.

Tested by:

1. Clearing logs
2. Loading mysite/feed.xml twice in a browser tab
3. Loading mysite/feed.json twice in a browser tab

I'm getting two hits for each content representation:

![Screen Shot](https://user-images.githubusercontent.com/243601/84594176-c2f9f800-ae50-11ea-807f-8c7887bd1032.png)

Good thing if it doesn't happen in Retour 3. :)

**Comment by distantnative** [comment]
Ok, so it at least looks like the same way I tested it.
Will work a bit more on Retour 3 and get back to you when it's close to release (not too long I hope), so you could maybe try whether it is actually fixed.

**Comment by distantnative** [comment]
> when it's close to release (not too long I hope)

The hopes or hybrid of the 2020 summer...
Anyways, it looks to me like this will be fixed with Retour 3.0.0 - which I expect to release still in 2020.

Please feel free to reopen if you still run into the issue with v3.
