### ISSUE TITLE
Update existing i18n files for Retour 3

### ISSUE THREAD

**Issue by distantnative** [distantnative/retour-for-kirby#177]
Retour 3 introduces a bunch of new language strings and renames most of the old ones. The existing language i18n files need to be updated accordingly.

I have added all new language strings in their English variant in comments to all languages, to make it easier to see what is missing.

## German ✅
- [x] Recycle existing language strings
- [x] Add new language strings

## French
https://github.com/distantnative/retour-for-kirby/blob/develop/config/i18n/fr.json
Original translation: @sylvainjule
- [x] Recycle existing language strings
- [ ] Add new language strings

## Brazilian Portuguese ✅
https://github.com/distantnative/retour-for-kirby/blob/develop/config/i18n/pt_BR.json
Original translation: @pedroborges
- [x] Recycle existing language strings
- [x] Add new language strings

## Turkish ✅
https://github.com/distantnative/retour-for-kirby/blob/develop/config/i18n/tr.json
Original translation: @afbora
- [x] Recycle existing language strings
- [x] Add new language strings

## How to help?
You can either [head over to Transifex and start translating](https://www.transifex.com/distantnative/retour-for-kirby) or you fork this repo (`develop` branch), edit the file and open a PR. You can send me an email to nico@getkirby.com - or you simply post the strings in this issue or open up a new issue.

Thanks a lot!

**Comment by pedroborges** [comment]
I'll submit a PR during this week ;)

**Comment by distantnative** [comment]
Hey everyone,
I thought I will make it a bit easier and use Transifex as we use for Kirby itself:
https://www.transifex.com/distantnative/retour-for-kirby

If you prefer any of the other ways, you can still do them and I will make sure to upload them to Transifex.
