### ISSUE TITLE
Panel browser history/$router via hash to parts

### ISSUE THREAD

**Issue by distantnative** [distantnative/retour-for-kirby#18]
Blocked by https://github.com/getkirby/kirby/issues/1470

**Comment by nilshoerrmann** [comment]
Is this related to having individual urls per plugin view? E. g. dashboard, redirect, fails, settings? If so, this would be very helpful especially if you'd like to share a view with clients or co-workers.

**Comment by distantnative** [comment]
Yes exactly, that's what this issue is about. But facing issues with the Panel, that doesn't like url hashes so far. Trying to sort that out soon.

**Comment by nilshoerrmann** [comment]
Great 👍
