### ISSUE TITLE
Table: sort by clicking on header

### ISSUE THREAD

**Issue by distantnative** [distantnative/retour-for-kirby#188]

**Comment by nilshoerrmann** [comment]
This non-permanent sorting would be very helpful when looking at existing routes or when browsing the most common errors.

There is also an usecase for permanent sorting that's pushed to the server: as far as I understand from trial and error, routes are processed from top to bottom as they are stored in `redirects.yml`. It would be great if I could resort routes manually to set precedence. To not conflict with virtual sorting by column, this feature could be made available when the table is sorted by index numbers.
