### ISSUE TITLE
Make SQLite logs optional

### ISSUE THREAD

**Issue by hdodov** [distantnative/retour-for-kirby#196]
We don't need the logging functionality of Retour. However, that functionality alone requires a whole Apache module for communication with the logs database, see #160. That's pretty inconvenient for a feature we have no use of.

It'd be very nice to be able to toggle logging and therefore - the dependency on SQLite. The panel view could also be simplified greatly. If the upcoming version of Retour is more modular, I think that could be an easy win.

**Comment by distantnative** [comment]
Already there, just set `distantnative.retour.logs` to `false`.

**Comment by hdodov** [comment]
Ha! That's **exactly** what I had in mind. Awesome!
