### ISSUE TITLE
Cant install 

### ISSUE THREAD

**Issue by smongey** [distantnative/retour-for-kirby#212]
Getting the following issue on install on a Kirby 3 project I’m working on which I have running locally. Any idea what might be the issue? 

![image](https://user-images.githubusercontent.com/1285493/88903036-ef27d780-d24a-11ea-956b-5f6d6bc12ddc.png)

**Comment by distantnative** [comment]
First thought would be that you might use an older Kirby version. What version are you on?

**Comment by smongey** [comment]
Wow, speedy reply. Kirby version is 3.3.6

**Comment by smongey** [comment]
I am running a local php server using php -S.

**Comment by distantnative** [comment]
The current release of Retour needs at least Kirby 3.4.0.

**Comment by distantnative** [comment]
@smongey has this solved your problem?
