### ISSUE TITLE
interference with securedpages plugin

### ISSUE THREAD

**Issue by demlak** [distantnative/retour-for-kirby#213]
## Describe the bug
there seems to be interference with securedpages plugin
(https://getkirby.com/plugins/kerli81/secured-pages)

## Steps to reproduce
1. use secured pages plugin
2. add a new route in retour
3. get error message on new route
```
TypeError thrown with message "Argument 1 passed to Plugin\SecuredPage\RouterAfterHook::process() must be an instance of Kirby\Cms\Page or null, instance of Kirby\Cms\Response given, called in /var/www/html/site/plugins/securedpages/index.php on line 29"

Stacktrace:
#10 TypeError in /var/www/html/site/plugins/securedpages/src/RouterAfterHook.php:10
#9 Plugin\SecuredPage\RouterAfterHook:process in /var/www/html/site/plugins/securedpages/index.php:29
#8 Kirby\Cms\App:Plugin\SecuredPage\{closure} in [internal]:0
#7 Closure:call in /var/www/html/kirby/src/Toolkit/Controller.php:49
#6 Kirby\Toolkit\Controller:call in /var/www/html/kirby/src/Cms/Event.php:168
#5 Kirby\Cms\Event:call in /var/www/html/kirby/src/Cms/App.php:199
#4 Kirby\Cms\App:apply in /var/www/html/kirby/src/Cms/App.php:330
#3 Kirby\Cms\App:Kirby\Cms\{closure} in /var/www/html/kirby/src/Http/Router.php:117
#2 Kirby\Http\Router:call in /var/www/html/kirby/src/Cms/App.php:333
#1 Kirby\Cms\App:call in /var/www/html/kirby/src/Cms/App.php:1018
#0 Kirby\Cms\App:render in /var/www/html/index.php:17

```

## Expected behavior
no error Message =)

## Specifications

  - Retour version: latest master.zip
  - Retour config options: default
  - Kirby version: latest

## additional
I don't know if this problem lays in your plugin or in the securedpages plugin.

**Comment by distantnative** [comment]
Based on the error message I'd think it's rather a bug (wrong assumption) in the other plugin

**Comment by demlak** [comment]
as far as i can see, the problem seems to be solved by latest commits of other plugin

**Comment by distantnative** [comment]
Closing this as it is a bug in the securedpages plugin.
