### ISSUE TITLE
Duplicate check icon in drawer component

### ISSUE THREAD

**Issue by johannschopplich** [distantnative/retour-for-kirby#219]
## Describe the bug

When adding or editing a route, the drawer component shows the check icon twice. I believe one shall be a simple close icon. It's not a bug by definition, but results in tricky UX.
Might origin in Kirby's drawer component itself. 

## Steps to reproduce

  1. Go to Retour settings.
  1. Add a route.

## Expected behavior

Closing icon indicating no changes are applied.

## Additional context

![grafik](https://user-images.githubusercontent.com/27850750/101284470-76302200-37e0-11eb-943a-81935da6ce5a.png)

## Specifications

  - Retour version: 3.0.0-RC.1
  - Retour config options: default
  - Kirby version: 3.5-RC.4
  - Browser: Firefox on macOS

**Comment by distantnative** [comment]
Oh yes, it used to be a X icon on the right (that wouldn't save changes). But Bastian seems to have changed this in the core. Have to think about a way...

Cause the blocks update on type (no way to cancel and discard). With the routes, I think I would like cancel and discard. Or maybe not. Have to think about it.

**Comment by johannschopplich** [comment]
I presumed it was a cancel icon once. 😋 I'm sure you will come up with a good way. Thanks!

**Comment by distantnative** [comment]
✅ will be fixed in release this week
