### ISSUE TITLE
Not possible to edit redirects path in drawer

### ISSUE THREAD

**Issue by chrfickinger** [distantnative/retour-for-kirby#222]
If the input field for the path is filled with the domain `<span class="k-input-before"></span>`, there is not enough space to see the entry and edit it reasonably (see screenshot).

![screenshot](https://user-images.githubusercontent.com/91317/106116967-d1ccbb00-6152-11eb-982b-21caaa6c8236.jpg)

**Comment by distantnative** [comment]
This seems to me like an issue of the Kirby core, not this plugin. Created an issue over there.

**Comment by chrfickinger** [comment]
But is it really necessaray to show always the complete domain here? It should be always the same, so actually it'S not really needed here no matter how long the domain entry is.

**Comment by distantnative** [comment]
When I started with Retour, I didn't have it in and I got multiple requests to show it to make clearer what the paths would be (and that you don't need to include the domain yourself).

However, I will make those first two field 1/1 and I'll also strip any `http://` and `www.` from the beginning of the domain.

**Comment by chrfickinger** [comment]
Thank you! I think a 1/1 field helps a lot :-)

**Comment by distantnative** [comment]
✅
