### ISSUE TITLE
Persistent table pagination

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#224]
If you set a custom pagination limit on a table, the interface forgets this setting when switching between tabs. It would be nice if the table limits were persisting.

**Comment by nilshoerrmann** [comment]
This happens without reloading the panel, just by switching tab context. So to clarify, this is not about storing limits across recurring visits or page refreshs, it's about navigating the tabs with the user staying in the current Vue context.

**Comment by distantnative** [comment]
✅ Sometimes it's the little typos... fixed in next release

**Comment by nilshoerrmann** [comment]
Thanks!
