### ISSUE TITLE
Route drawer interactions

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#226]
When adding or editing a route I noticed I got confused repeatedly with the existing click areas and the related actions:

![grafik](https://user-images.githubusercontent.com/25466/108995500-7c29f680-769d-11eb-974c-16a6d7c1c044.png)

- I often click on "select" instead of the checkmark to confirm a route.
- I often click on the input icon (the turning arrow) instead of "select" to choose a page destination.

The first issue has to do with contrast and sizing. I just oversee the checkmark.
The second interaction problem is related to the choice of icons, I guess. I think, I'd expect the plus icon to select pages similar to the pages field. Regarding the input icons, personally, I might prefer to not have any icons at all or to have an arrow between both inputs pointing from the left to right. But the latter is nothing common in the Kirby UI.

**Comment by distantnative** [comment]
Removing the field icons could be indeed an improvement, they aren't really needed and I could see how they distract people.

A plus icon for selecting a page doesn't sound intuitive to me either to be honest.

And the drawer is a core component, so I don't have control over the checkmark styling. Honestly, I'd prefer an explicit confirm/cancel drawer for Retour myself. But that's not available currently.

**Comment by distantnative** [comment]
✅
