### ISSUE TITLE
Timeline visualisation

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#227]
## What aspect in Retour bothers you and why?
Looking at the timeline makes me think that all issues have been resolved because the graph goes down to zero on the x axis:
![Bildschirmfoto am 2021-02-24 um 12 59 14](https://user-images.githubusercontent.com/25466/108997802-581be480-76a0-11eb-8179-f97096a12b2e.png)

## How would you improve it?
Cutting of at the current point in time would make the actual stats clearer:
![grafik](https://user-images.githubusercontent.com/25466/108997907-7bdf2a80-76a0-11eb-9365-b2509652a264.png) 

## How would this make Retour better?
The stats would be more accurate :)

**Comment by nilshoerrmann** [comment]
Maybe using a bar chart instead of a graph would be more true to the given data?

**Comment by distantnative** [comment]
I'll have to think about this for a while. Doesn't convince me immediately to not show data from the ongoing timeframe. And I think many are used to this visualization as it is used by Google Analytics and others... but I might change my mind when I think about this more.

**Comment by nilshoerrmann** [comment]
> Doesn't convince me immediately to not show data from the ongoing timeframe. 

That might be a misunderstanding from my quick mockup. My point was that it's a bit confusing to see the graph fall to zero _for the next month_ (or day, or year – depending on the set context). This makes it look as if there was a peek but everything has been resolved by now (it's down to zero again) which is not correct because the peek is happening right now.

> And I think many are used to this visualization as it is used by Google Analytics and others... 

I'm not a Google Analytics user so you might have a point here.

**Comment by distantnative** [comment]
Ok, I understood you now. This is hard since the chart library doesn't seem to support something like "draw (smooth) lines up until this data point, after that just drop to the next value (0)"

**Comment by nilshoerrmann** [comment]
Maybe this library might be interesting: https://chartscss.org/

**Comment by distantnative** [comment]
That looks great at a first look. Will give it a spin!

**Comment by distantnative** [comment]
Oh never mind it's 72kb - that's quite big

**Comment by nilshoerrmann** [comment]
Uh, I hadn't checked that!

**Comment by distantnative** [comment]
But it gave me ideas to try something else

**Comment by distantnative** [comment]
I think I am getting closer to a solution where it just cuts off the graph at today (this month/this year...)

<img width="1277" alt="Screen Shot 2021-03-24 at 12 05 23" src="https://user-images.githubusercontent.com/3788865/112300636-59d5c980-8c99-11eb-82ac-c561598bd532.png">

**Comment by nilshoerrmann** [comment]
That's a great direction because it emphasises the current stats. Thanks for working on the visualisation 👍

**Comment by distantnative** [comment]
✅ in [4.0.0-beta.1](https://github.com/distantnative/retour-for-kirby/milestone/23)
