### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by kaltschnitt** [distantnative/retour-for-kirby#230]
## Describe the bug

If disable logs in my config file, the api routes return an error because the database connection isn't established. The panel returns the following error: 

> Return value of distantnative\Retour\Log::db() must be an instance of Kirby\Database\Database, null returned

Quick fix for me: Removed line 77 and 79 in the file models/Retour.php

## Specifications

  - Retour version: 3.0.1
  - Kirby version: 3.5.1

**Comment by distantnative** [comment]
✅  Fixed in the next release

(your quick fix will spare you the error but negate the config setting that you don't want logs in some way)
