### ISSUE TITLE
Suggestion: Clearify Filtering Context

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#231]
When adjusting the date context in the Retour view, the tab "failures" gets filtered automatically, only showing the failed page loads from the given date range. This came to a surprise to me because it looked as if the date settings only affected the graph displayed (the dark and light style of the graph and the tabs make them look very self-contained) and because I was looking at the "routes" tab which – of course – didn't change. The filtering _makes sense indeed_ but there may be two possible changes to make the data context change easier to follow:

1. Moving the current date range and the corresponding navigation to a header element underneath the graph.
2. Switching to a light color scheme for the graph to connect both areas mor

This would make the interface more coherent to what the user is used to from the file or user views where the light and dark areas are more a reflection of what is happening below:

<img width="1478" alt="grafik" src="https://user-images.githubusercontent.com/25466/109779468-45586100-7c06-11eb-8942-3a4764fecf40.png">

---

<img width="1046" alt="grafik" src="https://user-images.githubusercontent.com/25466/109779031-d11dbd80-7c05-11eb-8e0d-24ca8c460053.png">

---

Additionally, it would be great if Retour was able to store the selected context across page loads. Currently, it reset to monthly display on refresh.

**Comment by distantnative** [comment]
You have a point here. I totally agree:
<img width="1365" alt="Screen Shot 2021-03-21 at 09 22 29" src="https://user-images.githubusercontent.com/3788865/111898542-fd6b7380-8a26-11eb-83ac-b9302f02037a.png">

**Comment by distantnative** [comment]
✅ in 4.0.0-beta.1
