### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by AhoyLemon** [distantnative/retour-for-kirby#232]
First of all, I'm just using this for the first time, and this plugin is fantastic! I love the UI.

Secondly, just a quick note....

The documentation is over here...

https://distantnative.com/retour/docs

..has [This](https://github.com/distantnative/retour-for-kirby/archive/master.zip) as the download link, which is ending in a 404 error, which seems like it's a GitHub side thing to prevent direct download links?

Anyway, if there's a better solution that's cool, but I just went to the [main repo page](https://github.com/distantnative/retour-for-kirby) and downloaded it from there.

**Comment by distantnative** [comment]
✅
