### ISSUE TITLE
[4.0.0-beta.1] Post route not working after update

### ISSUE THREAD

**Issue by guidoferreyra** [distantnative/retour-for-kirby#243]
## Describe the bug

After the update, a route in my config file that uses POST as method is not working anymore and I get the following error:

`Argument 4 passed to Kirby\Cms\App::distantnative\Retour\{closure}() must be of the type string or null, array given`

## Expected behavior

Its not supposed that Retour works here, there is no route or something related to this. And the route was working before the update.

## Specifications

  - Retour version: [4.0.0-beta.1]
  - Retour config options:
  - Kirby version: 3.5.3.1
  - Browser: Firefox, Chrome, etc

**Comment by distantnative** [comment]
Thanks, already know where the problem lies!

**Comment by distantnative** [comment]
This should be solved in the [first beta](https://github.com/distantnative/retour-for-kirby/releases/tag/4.0.0-beta.1). Please help me test the beta, so that we can make sure that the actual release works properly.
