### ISSUE TITLE
K3.6. replacing k-options-dropdown breaks fields

### ISSUE THREAD

**Issue by iskrisis** [distantnative/retour-for-kirby#252]
Hi Nico! I know this is on ice somewhat. Just for reference i thought i am going report this if somebody comes.

## Describe the bug
Retour replaces extends "k-options-dropdown" and that changed in 3.6 so it breaks some fields like when you want to use `uploads` on `files` field.

I know this is probably expected but it was not immediately noticeable. 

Cheers!

**Comment by distantnative** [comment]
This is solved by Retour 4.0 - [first beta](https://github.com/distantnative/retour-for-kirby/releases/tag/4.0.0-beta.1). Please help me test the beta, so that we can make sure that the actual release for sure doesn't suffer from the same problems as Retour 3 did.
