### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by fvwanja** [distantnative/retour-for-kirby#253]
Below the `path` field there is a text, informing me about placeholders for dynamic redirection (see screenshot). The link is broken since https://distantnative.com/retour/docs leads to a 443, connection refused.

Running on 3.0.0.

![screenshot](https://i.imgur.com/PMZciFN.jpeg)

🎄 Thanks in advance!

**Comment by distantnative** [comment]
This is solved by Retour 4.0 - [first beta](https://github.com/distantnative/retour-for-kirby/releases/tag/4.0.0-beta.1) is out.
