### ISSUE TITLE
Page picker for dialog fields

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#277]
It would be great, if redirect could not only be typed by hand but also selected via the page selector UI. This would help minimize typos for internal redirects.

**Comment by nilshoerrmann** [comment]
I just notices this is a duplicate of #75 and I'm the author 🙈

**Comment by distantnative** [comment]
I know :D and we had that feature. But currently Fiber dialogs didn't work well with opening a nested dialog for the page picker. So I had to remove it. Hope to bring it back down the road.
