### ISSUE TITLE
4.0: Path cut off

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#278]
Long domain names cut of the actual path that's edited.

![grafik](https://user-images.githubusercontent.com/25466/152806746-70e7bf51-b38f-4bb9-8750-94fac97c5d0f.png)

Ideas:

- make the path field content wrap
- display the domain outside the input field (help/info text)
- never show the domain (removing it – if present – when bluring the input)

**Comment by distantnative** [comment]
Using the standard `before` slot of a text field here, so neither wrapping nor hiding on blur are really attractive options as they'd mean hacking a default field. But maybe I just check how long the domain/before text is and if more than x characters, shorten it with `…`

**Comment by nilshoerrmann** [comment]
Regarding shortening: in my case, it would also work to only show the subfolder: `/example.com/` instead of `localhost:8888/example.com/`. This would make clear where to start with my path definition without filling the full input field.

**Comment by nilshoerrmann** [comment]
Other ideas: 

- Adding a flag in the config whether to show or hide the domain. I really like the domain to be displayed, but in my case it would make sense to disable it.
- Allowing to set a custom domain in the config (I could add the production domain for instance which is way shorter than my localhost).

**Comment by distantnative** [comment]
✅ There will be a new `distant native.retour.site` option that allows setting a custom text or to disable the prefix completely (`false`).
