### ISSUE TITLE
Failure categories: 404, exception...

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#281]
I'm currently testing Retour localhost while developing as site. I noticed that the plugin logs errors when an exception is thrown:

<img width="1438" alt="grafik" src="https://user-images.githubusercontent.com/25466/152810734-43387dfc-9df2-4948-aa93-df02e9106439.png">

It's true that the given path did not return a web page at that time but not because the route was outdated or incorrect but because the site failed to render due to an error in a template.

**Comment by distantnative** [comment]
But shouldn't a broken page with error in a template be reported as failure (Fehler) as well? Wouldn't you want to know that somewhere in your page apparently something is broken?

**Comment by nilshoerrmann** [comment]
Hmm … yes, that's not how I looked at it so far. I usually look at the list of errors to create new redirects wherever needed and exceptions don't have to be redirected but fixed in my templates. So in this case, I was irritated how it was possible that my root was throwing an error. Obviously that's where the exception occured but I was thinking of routes someone was trying to access. 

It's a useful feature though! It might need some kind of flag to understand that this is different to failing routes. Maybe the source could show a label "Exception"?

**Comment by distantnative** [comment]
@nilshoerrmann I had a closer look but given that Retour uses the `route:after` hook, I have not been able to think of any way how to get the information whether it's caused by an exception, missing page etc.

**Comment by nilshoerrmann** [comment]
While it would be nice to distinguish between a routing error and an exception, I'd close this case if it is too complex to solve. Maybe it's an idea to add a list to the docs which cases Retour cannot detect.
