### ISSUE TITLE
Format JSON for config file (pretty-print)

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#284]
When storing redirects as JSON in `retour.json`, updating routes from the panel UI remove all formatting. Storing the JSON with pretty formatting (line-breaks, indentations) would help reading the content in an external editor.

**Comment by distantnative** [comment]
I had another look at this, but with using the core `Data` classes, I have no influence on the formatting that the file is written. However, you could save it as PHP instead of JSON, then it gets written quite nicely formatted.
