### ISSUE TITLE
PHP8 really required?

### ISSUE THREAD

**Issue by teichsta** [distantnative/retour-for-kirby#301]
Hi @distantnative,

is PHP8 really required for retour 4.x? `composer.json` says "yes" but README states 7.4 (which would be good as i am not on 8, yet.

Thanks, Thomas E.-E.

**Comment by distantnative** [comment]
Doesn't composer say between (and including) 7.4 and 8.1?

**Comment by teichsta** [comment]
ups, sorry … i messed up things locally! Never mind!
