### ISSUE TITLE
Kirby 3.7 support

### ISSUE THREAD

**Issue by tobimori** [distantnative/retour-for-kirby#303]
composer.json locks to Kirby versions under 3.7.0

**Comment by S1SYPHOS** [comment]
Indeed it does, anything we can do to help?

**Comment by distantnative** [comment]
It's a safety net - to prevent user just start using it with 3.7 as there might be breaking changes. And I believe 3.7 actually breaks Retour in small ways. Will try to release a new version over the weekend

**Comment by distantnative** [comment]
I've made the necessary changes for Kirby 3.7. on the `develop` branch. Would be great if you could test them. I plan to release this as Retour 4.1 once Kirby 3.7 has been released.

**Comment by tobimori** [comment]
Works for me on first quick tests. :)

**Comment by tobimori** [comment]
It seems like the release is not yet available in composer, could you trigger a manual update on packagist? @distantnative

**Comment by distantnative** [comment]
Just did
