### ISSUE TITLE
Kirby (3.7.+) settings page is broken by Plugin

### ISSUE THREAD

**Issue by chrfickinger** [distantnative/retour-for-kirby#304]
See attached screenshot. It also destroys all other installed plugin views. The screenshot shows only retour installed.

![sc](https://user-images.githubusercontent.com/91317/175868274-88593eba-5cf8-4178-906e-2183d928f433.jpg)

**Comment by chrfickinger** [comment]
It also destroys the new added `layout: table` option for pages and files sections.

**Comment by distantnative** [comment]
You are using the develop branch of Retour?

**Comment by tobimori** [comment]
Retour develop branch fixes this.

**Comment by distantnative** [comment]
Not sure how @chrfickinger actually got the 4.0.0 release working with 3.7.0 - or did you tinker with the plugin code to remove the check? :D

**Comment by chrfickinger** [comment]
Of course i did not tinker the plugin code :-)
I installed the latest version 4.0 from here (no develop branch). But I have not yet started creating any redirects so far, because my project has just startet. I only relalized the views are broken with the plugin enabled.

**Comment by chrfickinger** [comment]
Installing the latest version solves the problem. Thank you for the quick solution!
