### ISSUE TITLE
[BUG] 404 when trying to "Add as redirect" in "Failures"

### ISSUE THREAD

**Issue by ieteo** [distantnative/retour-for-kirby#307]
## Describe the bug

The release [4.2.0](https://github.com/distantnative/retour-for-kirby/releases/tag/4.2.0) fixed the bug #300 when editing or removing path containing slashes from "Routes".  Thank you! 

However, the bug is still present when trying to "Add as redirect" from "Failures", which results in 404 error as described in #300 

This bug is only present on Apache when the `AllowEncodedSlashes` is set to `Off`

## Steps to reproduce

1. Get the Kirby starter kit and instal `distantnative/retour-for-kirby`

```sh
git clone https://github.com/getkirby/starterkit.git
cd starterkit
composer require distantnative/retour-for-kirby
```

2. Create `Dockerfile` with following content
```
FROM php:8.1-apache
RUN a2enmod rewrite
```

3. Build image and run the container
```sh
docker build -t starterkit .
docker run -p 80:80 -v "$PWD":/var/www/html starterkit
```

4. Call a non-existent URL containing slashes e.g. `http://localhost/sub/not-existing`
5. Go to http://localhost/panel, create user and log in
6. Go to `Rredirect` > `Failures` and `Add as redirect` the previously called non-existent URL

**Result:**
`404 Not Found` from Apache

_**Note**_
Removing path containing slashes under `Failures` also results in 404 error

## Expected behavior

modal opens up in order to add the path as redirect

## Context

- Kirby version: 3.7.5
- Retour version: 4.2.0
- Web Server: Apache with  `AllowEncodedSlashes Off`

**Comment by distantnative** [comment]
🙈

**Comment by ieteo** [comment]
I assume that changing this line:

https://github.com/distantnative/retour-for-kirby/blob/b74f5473f33603b7a1bfdaa1c9716b03998202b6/src/panel/components/Tabs/FailuresTab.vue#L65

to:
`const path = encodeURIComponent(row.path.replace(/\//g, "\x1D"));`

as what was done in:
https://github.com/distantnative/retour-for-kirby/blob/b74f5473f33603b7a1bfdaa1c9716b03998202b6/src/panel/components/Tabs/RedirectsTab.vue#L103

would hopefully also fix it in **FailuresTab**

**Comment by distantnative** [comment]
✅
