### ISSUE TITLE
Chart width on widescreen

### ISSUE THREAD

**Issue by afbora** [distantnative/retour-for-kirby#312]
![screen-capture-1465-Routes - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/193237114-7bad4f95-2ace-4f0e-b748-ac74530e1f92.png)

Is this expected view or bug on 1920x1080 screen?

I would expect it to be full width or aligned with the underlying container.

**Comment by distantnative** [comment]
I tried it the other way, but that looks even weirder when the background would cut off right at the edge of the graph.
