### ISSUE TITLE
Sorting queries for each column

### ISSUE THREAD

**Issue by DominiqueVial** [distantnative/retour-for-kirby#317]
Add the functionality to classify requests according to their number for all columns: path, referrer and processed requests.

Thus, by making them appear in descending order, it allows you to define priorities for resolving redirects: I will give priority to an error that has occurred 500 times rather than one that has occurred only once.

**Comment by distantnative** [comment]
https://github.com/distantnative/retour-for-kirby/assets/3788865/b3a8939e-64c6-431b-ae70-7e1ce0208dbd
