### ISSUE TITLE
Kirby 4 support

### ISSUE THREAD

**Issue by tobimori** [distantnative/retour-for-kirby#319]
I've tested the plugin, and it seems to work fine so far (registering redirects, using redirects & tracking 404s) - the only necessary change would be to update the version validation in `index.php`

![CleanShot 2023-06-15 at 10 54 45@2x](https://github.com/distantnative/retour-for-kirby/assets/29142128/e94355c0-5499-4e53-bacc-51a6cfb37044)

**Comment by distantnative** [comment]
For now altering this in your code is fine. There’ll be a few changes needed with an upcoming alpha to make it all nice, so I’m waiting for the Kirby alphas to be kinda stable before officially having a Retour (pre-)release.

**Comment by distantnative** [comment]
First beta release with support is out https://github.com/distantnative/retour-for-kirby/releases/tag/5.0.0-beta.1
