### ISSUE TITLE
[5.0-beta.1] Several errors on a fresh installation

### ISSUE THREAD

**Issue by tobimori** [distantnative/retour-for-kirby#321]
## Describe the bug
`Kirby\Toolkit\Date::isBefore(): Argument #1 ($datetime) must be of type DateTimeInterface|string|int, null given, called in /Users/tobimori/Developer/sew-morlaix/site/plugins/retour/src/Retour/Timespan.php on line 30` is shown when going to `/panel/retour/redirects`

`foreach() argument must be of type array|object, bool given` is also shown when I go to `/panel` or `/panel/login` (the redirect doesn't work)

- Kirby version: 4.0-alpha.7
I use the `intl` date handler if that makes a difference.

**Comment by distantnative** [comment]
Issue 1 is solved.

Issue 2 I see as well but not quite sure where it originates.

**Comment by tobimori** [comment]
fixed with 5.0.0-beta.2
