### ISSUE TITLE
[K4] Some K4 issues 

### ISSUE THREAD

**Issue by afbora** [distantnative/retour-for-kirby#326]
## Describe the bug

1. Hits always `–` but redirects working as expected. (also zero `redirected`, `resolved` and `failed` in graph)

![screen-capture-1683-Routes - Mægazine-localhost](https://github.com/distantnative/retour-for-kirby/assets/3393422/74ec2fda-8eb7-48ff-a4d5-5f0bf47c4fef)

2. `InvalidArgumentException: Invalid URL scheme: page`
a. Add new path `/any-path` from panel
b. Select redirect type a page (not absolute  url)
c. Select status 30x
d. Try to enter to the `/any-path` from frontend

![screen-capture-1682-Kirby CMS Debugger-localhost](https://github.com/distantnative/retour-for-kirby/assets/3393422/ad9aae8a-bda8-45d3-9944-f10485f94e20)

## Context

- Browser: Chrome
- Kirby version: 4.0-beta.1 
- Retour version: 5.0-beta.3
- Retour config: Default
- Subfolder kirby installation

**Comment by distantnative** [comment]
@afbora what view are you referencing? The screenshots aren't there

**Comment by afbora** [comment]
Description updated

**Comment by distantnative** [comment]
@afbora the date sector shows 1 Januar 2020 - are you sure there is any data (for redirected, Dailed...) for that date?

**Comment by distantnative** [comment]
Separate issue for the 2nd part which is clearly a bug: https://github.com/distantnative/retour-for-kirby/issues/327

**Comment by afbora** [comment]
I was testing the dates. I think I forgot to change them 🙈 So works as expected 👍
