### ISSUE TITLE
[v5] Redirects doesn't work if they contain a trailing slash

### ISSUE THREAD

**Issue by tobimori** [distantnative/retour-for-kirby#329]
![CleanShot 2023-09-26 at 23 01 50@2x](https://github.com/distantnative/retour-for-kirby/assets/29142128/966d6436-dcbd-41dd-a0c3-1ade952e14c0)

-> test2, doesn't work (even when adding the trailing slash in the url)
-> test, works

**Comment by nawalnew** [comment]
same here. I have a lot Urls with /. Hope someone get a fix for that

**Comment by distantnative** [comment]
@tobimori @nawalnew fixed in new beta https://github.com/distantnative/retour-for-kirby/releases/tag/5.0-beta.4
