### ISSUE TITLE
Cannot redirect to a page's content representation

### ISSUE THREAD

**Issue by fvsch** [distantnative/retour-for-kirby#336]
Congrats on the new Retour 5 release! The extension's panel UI looks great.

## Describe the bug

I’m using Retour 5 with Kirby 4 RC1.

My site has a `feed` page (`content/feed/feed.txt`) page, which uses a couple different templates to render an [Atom feed](https://en.wikipedia.org/wiki/Atom_(web_standard)) or a [JSON Feed](https://www.jsonfeed.org/):

```
content/
  feed/
    feed.txt
site/
  templates/
    feed.php
    feed.json.php
    feed.xml.php
```

This makes use of Kirby's [content representations feature](https://getkirby.com/docs/guide/templates/content-representations). The following 3 URLs use different templates:

- `/feed` → `site/templates/feed.php`
- `/feed.json` → `site/templates/feed.json.php`
- `/feed.xml` → `site/templates/feed.xml.php`

I also have a couple redirects that look like this:

```yaml
  -
    from: feed/articles
    to: feed.xml
    status: 301
  -
    from: feed/code
    to: feed.xml
    status: 301
```

The issue is that the HTTP responses for these redirections don't contain `Location: /feed.xml`, but instead they contain `Location: /feed`.

```sh
$ curl 'https://[my-site]/feed/articles' --include
HTTP/2 301
location: https://[my-site]/feed
content-type: text/html; charset=UTF-8
content-length: 0
```

It looks like internally this plugin calls to Kirby's API to retrieve the page for `'feed.xml'`, which selects the `content/feed` page, then it gets the page's URL, and that generates the URL for that page's default content representation instead of the intended content representation.

Some workarounds I’ve tried:

- use a leading slash (`to: /feed.xml`) → no difference
- use the path of a non-existing page (`to: somewhere/above/the/rainbow.xml`) → the `.xml` extension is kept in the resulting `Location` header, but that's not very useful since this is a bogus URL anyway
- use an absolute URL (`to: https://[my-site]/feed.xml`) → this one works

## Expected behavior

The extension in the redirection value should not be lost.

## Additional context

I reported a different issue with content representations back in 2020, I don’t know if that’s related in any way: https://github.com/distantnative/retour-for-kirby/issues/165

## Context

- Browser: any
- Kirby version: 4.0.0-rc.1
- Retour version: 5.0.0
- Retour config: default

**Comment by fvsch** [comment]
By the way, a related issue is that I tried creating a redirection like this:

```yaml
  -
    from: feed
    to: feed.xml
    status: 301
```

… and created a redirect loop since it kept redirecting `/feed` to `/feed`.

Dunno if that one would be fixable, though.

**Comment by distantnative** [comment]
Redirects to content representation should work with the next release
