### ISSUE TITLE
Redirect To field missing

### ISSUE THREAD

**Issue by squareclouds** [distantnative/retour-for-kirby#341]
hello,

i am using kirby 4.1 and the newest release of the plugin. somehow the field for the redirect to is not showing. any ideas?

![Bildschirmfoto 2024-02-05 um 11 49 18](https://github.com/distantnative/retour-for-kirby/assets/9073054/7fd343bd-86be-46b6-b09a-7a9272762421)

**Comment by squareclouds** [comment]
ok, i just found out that something is colliding with the link field plugin... i will try to find a solution for using them both in parallel

**Comment by distantnative** [comment]
Retour is using the native `link` field from Kirby 4. So if that gets replaced, it can break.
