### ISSUE TITLE
Accept closure for config storage path

### ISSUE THREAD

**Issue by tobimori** [distantnative/retour-for-kirby#345]
Not sure if this is already possible, but from looking at the docs it doesn't seem like so! 
Would be very helpful as the relative path turned out to be stored in /public on a different setup and not in the index/root one.

**Comment by distantnative** [comment]
At first I didn't remember either, but now looking at the code I think this should already work: https://github.com/distantnative/retour-for-kirby/blob/main/src/Retour/Config.php#L41-L46

Or maybe I am not understanding you/your use case fully.

**Comment by tobimori** [comment]
Honestly I also don't remember what the issue was when I wrote this. I'll close it for now.
