### ISSUE TITLE
Sorting columns in table in version 4.4 for kirby 3 websites

### ISSUE THREAD

**Issue by timluigjes** [distantnative/retour-for-kirby#346]
## What's your idea?

In previous versions it was possible to sort the table by clicking on the table header. This has been removed in newer versions and has been reintroduced in version 5 for kirby 4+. Is it possible to restore this for Kirby 3 websites?

**Comment by distantnative** [comment]
Sorry but I don't have the capacities to add new stuff to the Kirby 3 version unfortunately. I already have a hard time to find the time to regularly update the Kirby 4 version.
