### ISSUE TITLE
Redirect with sub-domain fails due to dual-parsing of target URL

### ISSUE THREAD

**Issue by twykr** [distantnative/retour-for-kirby#349]
## Describe the bug

Due to the code found in `src/Retour/Redirect.php` on lines 145-147, target URLs that have more than one period in the domain (e.g. `https://sub.domain.tld`) fail, due to being redirected to a partial domain (i.e. given the previous example, the target would end up as `https://sub.domain`).  

## Steps to reproduce

1. Create a new Retour redirect in the Kirby 4 CMS panel (e.g. `site.com/ggl`), with a target having a sub-domain (e.g. `https://accounts.google.com`)
2. Visit the redirect - which will, given the above example, will send you to `https://accounts.google`

## Expected behavior

Expected behavior is that the target redirect URL will be complete, as defined in the Kirby admin panel.

## Additional context

I believe the issue is caused by the `$to` value being recreated a second time, where it tries to split the target URL based on periods for some reason (I'm guessing the assumption is that only the domain will have periods, and there won't be any other periods in the URL?) - but the $placeholders variable is never given any other information - so when the `toPath()` method is called, the redirect ends up with a partial target URL.

The lines 145-147 are currently:

```
$to     = $redirect->to() ?? '/';
$parts  = Str::split($to, '.');
$to     = Redirect::toPath($parts[0], $placeholders);
```

Where 145 first defines the target URL as either the value stored in the data, or the root URL of the website.  However, lines 146-147 completely override that  - I'm guessing this is partial code trying to handle some special use case, and that it might be beta code that slipped into production, but was missed because normal on-site or non-subdomain redirects work in most instances.

If there's a reason why lines 146-147 cannot be removed, then I'd suggest replacing line 146 with the following conditional in the short-term, until the `$placedholders` functionality is finalized or fixed:

```
$parts  = count(Str::split($to,'.'))>2 ? array($redirect->to()) : Str::split($to,'.');
```

Alternatively, depending on the goal of the code in question, the `$placeholders` array needs to be properly populated, so that the `toPath()` method can construct the rest of the URL as the author desires.

## Context

- Browser: Chrome, Firefox, Brave
- Kirby version: 4.1.2
- Retour version: 5.2.0
- Retour config: Not sure what you want here - but we're using a standard setup of Retour on a Kirby 4 site, being run on Ubuntu / Apache with PHP 8.3.4

**Comment by distantnative** [comment]
Arg. Yea that's a nasty bug.

The code in question got added to allow redirecting to content representations of pages which feature an extension at the end of the path/url

**Comment by twykr** [comment]
> The code in question got added to allow redirecting to content 
> representations of pages which feature an extension at the end
> of the path/url

Ahh, gotcha.  In that case, may I make the suggestion to use the `parse_url()` function (https://www.php.net/parse_url) to pre-split the given target URL into the appropriate pieces, and use the results to run any permutations that you need, before reconstructing it into the goal URL? 

Alternatively, I'm sure you could come up with a regex that would parse only the path portion of the URL / ignoring the domain portion for your checks :)

**Comment by distantnative** [comment]
@twykr does it work for you with the following change? https://github.com/distantnative/retour-for-kirby/commit/602865fe641ba8beda1b4a2405ee57fc7ee44e0d

**Comment by twykr** [comment]
@distantnative - 

> does it work for you with the following change? 

Yes! That does seem to work better with the sub-domain redirects - thanks :)
I'm still not clear on where the `$placeholders` content is being set (line 147) - but as long as it works, I won't complain :D

Thanks again!

**Comment by distantnative** [comment]
@twykr they're all the values coming from the route patterns: https://github.com/distantnative/retour-for-kirby/commit/602865fe641ba8beda1b4a2405ee57fc7ee44e0d#diff-a4d9077198b0e15aec88e70d7cad2a58762db911032ba86ec98b9a37ee9d4677R143
