### ISSUE TITLE
No menu item in panel is created

### ISSUE THREAD

**Issue by weedukind** [distantnative/retour-for-kirby#350]
## Describe the bug
The menu item `redirects` in the panel to the retour plugin is not shown.
The url to the plugin `https://yourwebsite.com/panel/retour` returns `The view could not be found`.

## Steps to reproduce

1. Install Kirby 3.9.8.1 on PHP 8.1.27
2. Install plugin with composer: `composer require distantnative/retour-for-kirby:3.0.0.`
3. Log into panel as admin `https://yourwebsite.com/panel` -> Check menu
4. Try to call `https://yourwebsite.com/panel/retour`

## Expected behavior
- Main navigation of panel contains menu item `redirects` in order to administrate redirect plugin.
- `https://yourwebsite.com/panel/retour` should lead to administration of redirect plugin.

## Additional context

It should look like:
<img width="133" alt="Bildschirmfoto 2024-04-25 um 12 47 59" src="https://github.com/distantnative/retour-for-kirby/assets/5358341/46964630-2266-49e5-9e15-888074b67501">

It actually does look like:
<img width="133" alt="Bildschirmfoto 2024-04-25 um 12 59 44" src="https://github.com/distantnative/retour-for-kirby/assets/5358341/5cc65706-1ea0-4c16-b9b2-47529c863119">

## Context

- Browser: Version 124.0.6367.62 (Offizieller Build) (arm64)
- Kirby version: 3.9.8.1
- Retour version: 3.0.0
- Retour config: not exactly sure what is meant, but no file in retour-for-kirby is touched

**Comment by weedukind** [comment]
retour-for-kiry 4.4.1 works with kirby 3.9.8.1.

I suggest to tag retour-for-kiry 3.0.0 not to work with kirby 3.9.8.1.

**Comment by distantnative** [comment]
The docs do recommend to use Retour 4.4.2 for Kirby 3. How did you end up starting with Retour 3.0.0?

**Comment by weedukind** [comment]
I first did not specified a version `composer require distantnative/retour-for-kirby` which ended up in a composer error.
Than I picked 3.0.0 since we use it in a different Kirby project (3.6.x). Composer did no complaint and installed the plugin. It was also listed in the Kirby plugin list in the panel.

**Comment by distantnative** [comment]
> It was also listed in the Kirby plugin overview in the panel.

It can only be listed there if the plugin was already installed. 

Closing this as using the proper Retour version solved the issue :)
