### ISSUE TITLE
Wrong composer name on plugins.getkirby.com

### ISSUE THREAD

**Issue by FynnZW** [distantnative/retour-for-kirby#362]
A small mistake I just noticed, on https://plugins.getkirby.com/distantnative/retour it says
`composer require distantnative/retour` 
instead of
`composer require distantnative/retour-for-kirby`

![Screen 2024-11-19 at 15 24 51@2x](https://github.com/user-attachments/assets/44a58cde-9d7c-4412-8540-efacfb823c59)

**Comment by distantnative** [comment]
Just realized this is actually because I have it wrong in the `composer.json`.
