### ISSUE TITLE
ZIP install throws error

### ISSUE THREAD

**Issue by jschopplich** [distantnative/retour-for-kirby#48]
Good evening, 

I just tried to install your plugin at https://github.com/distantnative/retour-for-kirby/commit/6a363f4e14cdd09b6dfd2e9f6642add05628a9ea and get the following error:

```
Fatal error: Uncaught Error: Class 'distantnative\Retour\Retour' not found in [...]\site\plugins\retour\index.php:12 Stack trace: #0 [...]\kirby\src\Cms\AppPlugins.php(501): include_once() #1 [...]\kirby\src\Cms\AppPlugins.php(467): Kirby\Cms\App->pluginsLoader() #2 [...]\kirby\src\Cms\AppPlugins.php(335): Kirby\Cms\App->plugins() #3 [...]\kirby\src\Cms\App.php(116): Kirby\Cms\App->extensionsFromPlugins() #4[...]\index.php(5): Kirby\Cms\App->__construct() #5 {main} thrown in [...]\site\plugins\retour\index.php on line 12
```

The `master` branch still works fine. It has probably something to do with your PHP class refactor yesterday.

**Comment by distantnative** [comment]
Can confirm the bug - looking into it right now (the `develop` branch is never save in that early stage ;) )

**Comment by distantnative** [comment]
Ah, already know what's wrong: It's a bug in Kirby that will be fixed with Kirby 3.0.2 - I know, the RC isn't even out for that. Let me fix it for the plugin (it has to do with capitalisation), so 3.0.1 should work as well.

**Comment by jschopplich** [comment]
Ah right. Thanks for fixing temporarily!

**Comment by distantnative** [comment]
Try https://github.com/distantnative/retour-for-kirby/commit/0c67098d20cd90e67a537fff8f4a74440e21ec5d - that should work. However, data structure has changed a bit from beta 2 to now. You might want to clear all logs. I am sorry for that but I try to rather work these things out now than after the first final 1.0.0

**Comment by distantnative** [comment]
And thanks for letting me know - happy to see that someone is giving this a try :D

**Comment by distantnative** [comment]
@jschopplich Let me know if you encounter any other issues, bugs or things where you'd like to see improvements, features etc.

**Comment by jschopplich** [comment]
> Try [0c67098](https://github.com/distantnative/retour-for-kirby/commit/0c67098d20cd90e67a537fff8f4a74440e21ec5d) - that should work. However, data structure has changed a bit from beta 2 to now. You might want to clear all logs. I am sorry for that but I try to rather work these things out now than after the first final 1.0.0

No problem at all. If I use beta software, it's my responsibility. I rather prefer big fixes than workarounds which in the end cause every developer long-term headaches.

> And thanks for letting me know - happy to see that someone is giving this a try :D

Was following along quietly this weekend. 🙂 

> @jschopplich Let me know if you encounter any other issues, bugs or things where you'd like to see improvements, features etc.

Will do! I will test our plugin more extensively next week.
