### ISSUE TITLE
Redirect for home not working

### ISSUE THREAD

**Issue by distantnative** [distantnative/retour-for-kirby#56]
>I can’t seem to be able to set up a home redirect.
putting in / doesn’t redirect at all, shows the home content which is default, but title shows ‘error’ and fails count goes up
leaving it blank results in a white screen with no content.
>Edit: I was able to redirect home with a 301, not 200 which I had before. 200 appears to work redirecting anywhere but home.

**Comment by distantnative** [comment]
✅

**Comment by iskrisis** [comment]
I don't understand this change. If i redirect to "/" i expect it to go "/" not "home" (my home is different then "home" and i really want to go "/"). If i comment it out it seems to work just fine even with 200 and 301. Isn't it something that has fixed itself now because of other fixes?
