### ISSUE TITLE
Retour breaks template components

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#60]
I noticed that language handling was broken with Retour in Kirby 3.0.2 as is already tracked in #53. This seems to work again using the latest Kirby `develop` branch. But now custom template components are broken: the template components are never called.

The component definitions looks like this:

```php
Kirby::plugin('hananils/xslt', [
    'components' => [
        'template' => function (App $kirby, string $name, string $contentType = null) {
            return new Hananils\Xslt($name, $contentType);
        }
    ],
    'collections' => [
        'assets' => require 'collections/assets.php',
        'datetime' => require 'collections/datetime.php'
    ]
]);
```

The `template` function is never called. Removing Retour fixes this issue.

**Comment by bnomei** [comment]
@distantnative if fixed please quickly explain what went wrong. i am kind of curious if my plugins using route hooks might cause similar problems.

**Comment by nilshoerrmann** [comment]
@bnomei: A guess on Slack was that this is related to a call to `kirby()` before the main Kirby instance is initialized. That's also what seems to cause the language issues in #53.

**Comment by jschopplich** [comment]
@nilshoerrmann Exactly.
@bnomei Nico and Bastian are working on a fix already. Hopefully we can use the `kirby()` helper in plugins and e.g. `kirby()->root()` in the near future safely.

**Comment by distantnative** [comment]
Should be fixed in upcoming beta. Please feel free to re-open if problems remain.

**Comment by nilshoerrmann** [comment]
Cool, thanks!
