### ISSUE TITLE
Retour artefacts after uninstall

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#61]
I've just uninstalled Retour by removing the submodule. This leaves me with this artefact in the main menu (see the `view.retour` entry):

<img width="149" alt="grafik" src="https://user-images.githubusercontent.com/25466/53091202-a2968380-3511-11e9-8bbe-0d596b0b659e.png">

Is there any clean-up job needed or is this an Kirby issue?

**Comment by distantnative** [comment]
I’d say that’s a Kirby issue!

**Comment by nilshoerrmann** [comment]
https://github.com/getkirby/kirby/issues/1491
