### ISSUE TITLE
Redirect to external Sharepoint Links dont work

### ISSUE THREAD

**Issue by saschen** [distantnative/retour-for-kirby#63]
A external Link like:
https://xy-my.sharepoint.com/:v:/p/sl/EFLs-R647p1Jp0z70jufZ_tG4L8CrDL_tIYGjsMYmu8sw?e=HGbZ32
do not work.

It redirects to:
https://xy-my.sharepoint.com/p/sl/EFLs-R647p1Jp0z70jufZ_tG4L8CrDL_tIYGjsMYmu8sw?e=HGbZ32

The path with: `/:v:/ `will be removed

Workarround: use %3A instead of :

**Comment by distantnative** [comment]
This seems to be caused in the Kirby core. I created an issue for that. https://github.com/getkirby/kirby/issues/1522

**Comment by distantnative** [comment]
I finally realized `:v:` is treated by Kirby as parameter, so this can't be solved with Kirby. I'm sorry.
