### ISSUE TITLE
Plugin doesnt work after installation.

### ISSUE THREAD

**Issue by WeTurkstra** [distantnative/retour-for-kirby#68]
I have installed the plugin using composer:
```composer require distantnative/retour-for-kirby```
It installed the 1.0.0-beta.4

When i navigate to `/panel/plugins/retour` i get:
Cannot create property 'column-status' on boolean 'true'

**Comment by distantnative** [comment]
Ok, good news: I can reproduce the error. Bad news: I still have to find its origin and fix it.

**Comment by distantnative** [comment]
I just published beta 5 which should fix your problem: https://github.com/distantnative/retour-for-kirby/releases/tag/1.0.0-beta.5
