### ISSUE TITLE
Status selection

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#72]
When selecting the status code for a redirect, it's possible to click the text to get the select options but clicking the arrow on the right does nothing.

This might be a general Kirby issue.

_Latest Firefox on macOS Mojave._

**Comment by distantnative** [comment]
Let me check later, but I'd guess that's rooted in Kirby's select field in general.

**Comment by distantnative** [comment]
Nope, my mistake. Will be fixed in next beta ✅
