### ISSUE TITLE
Resolved fails

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#73]
After creating a redirect for a failed request, it would be nice if this request would be marked as resolved in the stats and graphs.

**Comment by distantnative** [comment]
Great idea for the"Fails" view.
For the graphs mayeb still a good idea, but the way the plugin stores historic data (aggregated), I don't think it will be possible to reassign those.

**Comment by distantnative** [comment]
✅ for version 2 (needed to switch to a database instead of textiles for the log) - all what you asked for :D
