### ISSUE TITLE
Page selector

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#75]
On the redirect view, it would be nice to have a page selector for the redirect similar to the core pages field. Choosing a page would automatically insert the page link into the redirect field.

**Comment by distantnative** [comment]
Thanks for the idea. I think I'm open to it, but after 1.0 (I finally want to get out a first stable version).

**Comment by nilshoerrmann** [comment]
Oh, no worries and no hurries. 
I'm just jotting down ideas :)

**Comment by distantnative** [comment]
Appreciated!

**Comment by distantnative** [comment]
✅

**Comment by distantnative** [comment]
Sneak preview:
<img width="1132" alt="Screen Shot 2019-07-30 at 13 19 02" src="https://user-images.githubusercontent.com/3788865/62125159-9f779e80-b2cc-11e9-971f-455b406b66df.png">
