### ISSUE TITLE
Plugin does not work in composer/vendor setup

### ISSUE THREAD

**Issue by macx** [distantnative/retour-for-kirby#79]
I'm using a custom folder setup, but this plugin is not working. Regarding to the README, I should update paths in my index.php. Unfortunately the link provided in your README is not working.

**Comment by distantnative** [comment]
Could you let me know your setup? Then I will try to tell you how to make it work - custom folder setups are still tricky in plugins unfortunately.

**Comment by macx** [comment]
@distantnative Sure.

```php
<?php

$base = dirname(__DIR__);

require $base . '/vendor/autoload.php';

$kirby = new Kirby([
  'roots' => [
    'index'    => __DIR__,
    'base'     => $base,
    'content'  => $base . '/dist/content',
    'site'     => $src = $base . '/src',
    'storage'  => $storage = $src . '/storage',
    'accounts' => $storage . '/accounts',
    'cache'    => $storage . '/cache',
    'sessions' => $storage . '/sessions'
  ]
]);

echo $kirby->render();
```

**Comment by distantnative** [comment]
Do you get a specific error message (PHP or Javascript in console)?

**Comment by macx** [comment]
Nothing at all:

![image](https://user-images.githubusercontent.com/84112/54305594-edaf2e00-45c7-11e9-8846-9c38e56077ca.png)

**Comment by distantnative** [comment]
And in the Panel? Does it show at all?

**Comment by macx** [comment]
No, nothing there as well. I'm using a custom layout in `site.yml`.

**Comment by distantnative** [comment]
But it doesn’t “live” on the `site.yml` but on its separate view. You should find it in the top bar menu as entry. It’s not there?

**Comment by macx** [comment]
OK, I got it: I installed all plugins in `vendor` and they worked nicely. Your plugin only works in the `site` folder (in my custom setup it's `src`), but not in `vendor`. As a workaround I moved my plugins to `src/plugins`, but it would be nice if your plugin is less restrict.

**Comment by distantnative** [comment]
Ah grea,t thanks for that info, that helps a lot. Will try to make it work from vendor over the weekend.

**Comment by distantnative** [comment]
@macx I am a bit lost here. I thought even via composer the plugin would be installed into site/plugins. Could you share a bit more info on your setup, so I can try to reproduce this?

**Comment by distantnative** [comment]
@macx I cannot reproduce this. Please reopen this issue when you can provide more information.
