### ISSUE TITLE
Some user languages breaks Retour

### ISSUE THREAD

**Issue by olach** [distantnative/retour-for-kirby#81]
If the user has set the user language to a language with a underscore in the language code (sv_SE, pt_PT, pt_BR etc) the Retour plugin won't load. Instead an error is shown: `Invalid language tag: sv_SE`

![image](https://user-images.githubusercontent.com/1300644/55944831-be80f080-5c49-11e9-8fca-dbb7949bff33.png)

This error occurs in Firefox and Chrome, but not in Safari for some reason.

Kirby 3.1.2
Retour 1.0.0

**Comment by olach** [comment]
Sorry for being to quick here. Just tested this plugin on another site, and this issue seems isolated to just one specific site of mine. I will have to investigate further what can cause this. Must be a custom setting somewhere.

**Comment by olach** [comment]
I have tried to locate the problem but with no luck.

The dev console outputs this:

```
app.js:1 RangeError: Invalid language tag: sv_SE
    at Date.toLocaleString (<anonymous>)
    at a.getValue (index.js:60)
    at index.js:60
    at a.Re [as _l] (vendor.js:41)
    at index.js:60
    at a.Re [as _l] (vendor.js:41)
    at a.render (index.js:60)
    at a.t._render (vendor.js:41)
    at a.r (vendor.js:41)
    at or.get (vendor.js:41)
```

**Comment by olach** [comment]
Ok, I have found the problem. You are using the js function `toLocaleString()`. When passing the locale argument, the function expects the locale in the form of `sv-SE`, but Kirby uses `sv_SE` internally.

To fix this, you need to replace `_` into `-` in the locale string before passing it to the function.

Read more:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#Using_locales

**Comment by distantnative** [comment]
Thanks for the digging!

**Comment by distantnative** [comment]
✅
