### ISSUE TITLE
Safari problem with Dates

### ISSUE THREAD

**Issue by olach** [distantnative/retour-for-kirby#83]
In Safari, instead of dates, `Invalid Date` is shown:

![image](https://user-images.githubusercontent.com/1300644/55948807-92696d80-5c51-11e9-9a32-06a1791cd407.png)

![image](https://user-images.githubusercontent.com/1300644/55948826-9a291200-5c51-11e9-97f8-894f095d2707.png)

Chrome and Firefox shows dates correctly.

Kirby 3.1.2
Retour 1.0.0

**Comment by distantnative** [comment]
I have not forgotten this - will tackle your issues over the next two weeks.

**Comment by olach** [comment]
No worries. This is not a dealbreaker. The other issues have I solved with some custom fixes in my code. So the plugin is up and running on a live site.

**Comment by distantnative** [comment]
I finally figured out it#s because of the date format I store the logs, which Chrome and Firefox can handle, Safari not. I'll postpone this issue for a later version, since I have plans to rework the data storage anyways.

**Comment by distantnative** [comment]
✅
