### ISSUE TITLE
Localized date format

### ISSUE THREAD

**Issue by afbora** [distantnative/retour-for-kirby#91]
![FireShot Capture 720 - Kirby Panel - http___pixelshop com_panel_plugins_retour](https://user-images.githubusercontent.com/3393422/62112222-f1afc400-b2ba-11e9-9b58-cc2822deb96c.png)

I think it would be better to use the locale of the panel language.

**Current Dates**: 29 July - 4 August 2019
**Expected Dates**: 29 Temmuz - 4 Ağustos 2019

**Comment by distantnative** [comment]
I am having a hard time with this:
I need to use `setlocale` on the PHP part, which expects me to pass e.g. `de_DE` for German.
But I only get shortened versions of the users' language from the Panel, e.g. `de`.
So I am not sure if I can implement this with the information the Panel provides.

**Comment by afbora** [comment]
I got the issue. So we need something like that class:
https://github.com/peterkahl/Country-to-Locale

Or as an easier and stable solution we can add option `date handler` (default: `date`) like that:

```
Kirby::plugin('distantnative/retour', [
  'options' => [
    'date'  => [
        'handler' => 'strftime',
        'locale' => 'tr_TR'
    ]
  ]
]);
```

That makes more sense to me.

**Comment by distantnative** [comment]
Thanks for the pointer, I will have a look at the library.

The option has the issue that it would be fixed and not per Panel user

**Comment by afbora** [comment]
> The option has the issue that it would be fixed and not per Panel user

You right! I missed that.

**Comment by distantnative** [comment]
Seems to work with the library ✅
